### ISSUE TITLE
getting javaScript heap out of memory

### ISSUE THREAD

**Issue by BhaskaranR** [dfuse-io/demux-js-dfuse#1] opened 2019-08-11 20:27 UTC
not sure if this library is ready to use. but getting this error on kylin testnet.

```Processing block 50545756... (source=BaseActionWatcher)
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
{"sour
<--- Last few GCs --->

[15436:0x110000000]    55580 ms: Scavenge 1277.2 (1431.3) -> 1264.7 (1433.8) MB, 5.0 / 0.0 ms  (average mu = 0.233, current mu = 0.203) allocation failure 
[15436:0x110000000]    55611 ms: Scavenge 1280.6 (1434.8) -> 1268.0 (1437.3) MB, 5.0 / 0.0 ms  (average mu = 0.233, current mu = 0.203) allocation failure 
[15436:0x110000000]    55634 ms: Scavenge 1284.0 (1438.3) -> 1271.4 (1439.3) MB, 4.6 / 0.0 ms  (average mu = 0.233, current mu = 0.203) allocation failure 
```

**Comment by olivierbeaulieu** [comment] 2019-08-12 15:50
Hey @BhaskaranR!

Thanks for opening an issue. Could you provide me with a reproductible code example so I can look into this issue?

Thanks

**Comment by BhaskaranR** [comment] 2019-08-12 20:02
run the example from the fork. keep the app up for a while and the program terminates
https://github.com/BhaskaranR/demux-js-postgres

**Comment by olivierbeaulieu** [comment] 2019-08-12 20:20
The fork you linked does not seem to use `demux-js-dfuse`, is this the right link?

**Comment by BhaskaranR** [comment] 2019-08-12 20:38
sorry posted the wrong link 
https://github.com/BhaskaranR/demux-js-dfuse

**Comment by olivierbeaulieu** [comment] 2019-08-12 21:09
Ok, I'm looking into this. You simply ran `DFUSE_API_KEY=******** yarn start` and it failed? Is this something that happened quickly, or it failed after a few hours?

**Comment by BhaskaranR** [comment] 2019-08-12 22:31
Yes, It happens after a few minutes. Were you able to replicate?

**Comment by olivierbeaulieu** [comment] 2019-08-12 23:21
It's been running for about an hour now, it seems to be working fine over here. Could you give me the full logs of a reproduction on your side, as well as the specs of the machine you are running this on?

**Comment by BhaskaranR** [comment] 2019-08-13 03:17
MacOS Mojave
3.2 GHz Intel Core i7
32 GB 2667 MHz DDR4
Intel UHD Graphics 630 1536 MB

```FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[22207:0x108000000]   534303 ms: Mark-sweep 624.9 (669.7) -> 624.9 (634.7) MB, 111.4 / 0.0 ms  (average mu = 0.930, current mu = 0.000) last resort GC in old space requested
[22207:0x108000000]   534406 ms: Mark-sweep 624.9 (634.7) -> 624.9 (634.7) MB, 103.0 / 0.0 ms  (average mu = 0.871, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x6ddd3bcfc7d]
Security context: 0x0c974c59d9b1 <JSObject>
    1: /* anonymous */ [0xc97b93a1a19] [/Users/bhaskaran/Documents/demux-js-dfuse/node_modules/demux/dist/AbstractActionHandler.js:~198] [pc=0x6ddd403f12b](this=0x0c970cf83749 <AbstractActionHandler map = 0xc9740e11ca1>)
    2: next [0xc974c5993c1](this=0x0c97b93a0989 <JSGenerator>)
    3: /* anonymous */ [0xc97b93a1fc1] [/Users/bhaskaran/Documents/demux-js-d...

 1: 0x1000667f8 node::Abort() [/usr/local/bin/node]
 2: 0x100066f48 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x1001b50d7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1001b5074 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1005bbfb2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x1005c5594 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 7: 0x10059ef17 v8::internal::Factory::CopyWeakArrayListAndGrow(v8::internal::Handle<v8::internal::WeakArrayList>, int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 8: 0x1006fd8ca v8::internal::PrototypeUsers::Add(v8::internal::Isolate*, v8::internal::Handle<v8::internal::WeakArrayList>, v8::internal::Handle<v8::internal::Map>, int*) [/usr/local/bin/node]
 9: 0x1006e6ba7 v8::internal::JSObject::LazyRegisterPrototypeUser(v8::internal::Handle<v8::internal::Map>, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x1007040d6 v8::internal::Map::GetOrCreatePrototypeChainValidityCell(v8::internal::Handle<v8::internal::Map>, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x100630c3e v8::internal::LoadHandler::LoadFromPrototype(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Smi>, v8::internal::MaybeObjectHandle, v8::internal::MaybeObjectHandle) [/usr/local/bin/node]
12: 0x100636aa1 v8::internal::LoadIC::ComputeHandler(v8::internal::LookupIterator*) [/usr/local/bin/node]
13: 0x10063592d v8::internal::LoadIC::UpdateCaches(v8::internal::LookupIterator*) [/usr/local/bin/node]
14: 0x10063551c v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/usr/local/bin/node]
15: 0x10063c511 v8::internal::Runtime_LoadIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
16: 0x6ddd3bcfc7d 
17: 0x6ddd403f12b 
18: 0x6ddd4021594 
✨  Done in 535.46s.
```

**Comment by olivierbeaulieu** [comment] 2019-08-13 14:45
Ok great, I managed to reproduce it! I am investigating the cause and will let you know as soon as this is fixed.

**Comment by BhaskaranR** [comment] 2019-08-15 14:59
hi, were you able to find a solution?

**Comment by olivierbeaulieu** [comment] 2019-08-15 15:50
Hey @BhaskaranR! Yes, I found a solution. It involves a change in demux-js itself - I'm talking with it's maintainer. I think a fix might be available today.

**Comment by olivierbeaulieu** [comment] 2019-08-15 21:09
A [PR](https://github.com/EOSIO/demux-js/pull/173) has been opened on demux-js, once it is merged we will be able to resolve this issue. Thank you for your patience!

**Comment by BhaskaranR** [comment] 2019-08-16 02:32
Thank you!

**Comment by olivierbeaulieu** [comment] 2019-08-19 14:16
@BhaskaranR I have pushed the fix to the master branch. The PR on demux-js isn't merged yet, but I made master point to my fork of demux-js in the meantime. Can you rebase your changes on the new code?

Important note: the `validateBlockHashes` parameter has been renamed to `validateBlocks`. Your example code will need to reflect that.

Let me know if that works for you. I ran your example locally, and everything seems to run smoothly now.

**Comment by BhaskaranR** [comment] 2019-08-21 18:12
don't see the issue now. will keep an eye. thank you

**Comment by olivierbeaulieu** [comment] 2019-08-21 20:32
Thanks! I'll close the issue, let me know if anything else comes up.

**Closed as completed by olivierbeaulieu** 2019-08-21 20:32 UTC
